name: Fetch & Convert Leader Portraits

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # 毎週日曜 UTC 0時
  workflow_dispatch:

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl imagemagick

    - name: Fetch and convert portraits
      run: |
        mkdir -p portraits

        # tag_filename : "表示名（Wikipediaタイトル）"
        declare -A leaders=(
          ["CHI_xi_jinping"]="Xi Jinping"
          ["RAJ_narendra_modi"]="Narendra Modi"
          ["VNM_bao_dai"]="Bảo Đại"
        )

        for key in "${!leaders[@]}"; do
          TAG="${key%%_*}"
          FILE="${key#*_}"
          TITLE="${leaders[$key]}"

          echo "▶ Fetching portrait for: $TITLE (→ gfx/leaders/$TAG/$FILE.dds)"

          API_TITLE=$(echo "$TITLE" | sed 's/ /_/g')
          API_URL="https://en.wikipedia.org/w/api.php?action=query&titles=${API_TITLE}&prop=pageimages&format=json&pithumbsize=512"

          IMG_URL=$(curl -s "$API_URL" | grep -oP '"source":"\K[^"]+')

          if [ -n "$IMG_URL" ]; then
            mkdir -p "gfx/leaders/$TAG"
            curl -sL "$IMG_URL" --output "portraits/$FILE.jpg"
            convert "portraits/$FILE.jpg" -resize 156x210\! "gfx/leaders/$TAG/$FILE.dds"
            echo "✅ Saved: gfx/leaders/$TAG/$FILE.dds"
          else
            echo "⚠ Failed to find image for $TITLE"
          fi
        done

    - name: Commit and Push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add gfx/leaders/**/*.dds
        git diff --cached --quiet || git commit -m "Auto: Update leader portraits (CHI, RAJ, VNM)"
        git push
