name: Fetch & Convert Leader Portraits

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget imagemagick

    - name: Fetch and convert portraits
      run: |
        mkdir -p portraits

        # key = tag_filename / value = 表示名（アクセントつきOK）
        declare -A leaders=(
          ["CHI_xi_jinping"]="Xi Jinping"
          ["RAJ_narendra_modi"]="Narendra Modi"
          ["VNM_bao_dai"]="Bao Dai"
        )

        for key in "${!leaders[@]}"; do
          TAG=$(echo "$key" | cut -d_ -f1)
          FILE=$(echo "$key" | cut -d_ -f2-)
          NAME="${leaders[$key]}"

          echo "▶ Fetching portrait for: $NAME → gfx/leaders/$TAG/$FILE.dds"

          # スペースをアンダースコアにしてエンコード
          TITLE=$(echo "$NAME" | sed 's/ /_/g')
          API_URL="https://en.wikipedia.org/w/api.php?action=query&titles=${TITLE}&prop=pageimages&format=json&pithumbsize=512"

          IMG_URL=$(curl -s "$API_URL" | grep -oP '"source":"\K[^"]+')

          if [ -n "$IMG_URL" ]; then
            mkdir -p "gfx/leaders/$TAG"
            wget -q -O "portraits/$FILE.jpg" "$IMG_URL"
            convert "portraits/$FILE.jpg" -resize 156x210\! "gfx/leaders/$TAG/$FILE.dds"
            echo "✅ Saved: gfx/leaders/$TAG/$FILE.dds"
          else
            echo "⚠ Failed to find image for $NAME"
          fi
        done

    - name: Commit and Push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add gfx/leaders/**/*.dds
        git diff --cached --quiet || git commit -m "Auto: Update leader portraits (CHI, RAJ, VNM)"
        git push
