name: Fetch & Convert Leader Portraits by Country

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # 毎週日曜 UTC 0時に実行
  workflow_dispatch:

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget imagemagick cmake g++ git
        git clone https://github.com/castano/nvidia-texture-tools.git
        cd nvidia-texture-tools
        cmake .
        make -j$(nproc)
        sudo cp nvcompress /usr/local/bin/

    - name: Fetch and convert portraits
      run: |
        mkdir -p portraits

        # 国家タグと名前・ファイル名の明確な対応
        declare -A leaders

        # 中国 CHI
        leaders["CHI_xi_jinping"]="Xi Jinping"
        # インド IND
        leaders["IND_narendra_modi"]="Narendra Modi"
        # ベトナム VNM
        leaders["VNM_bao_dai"]="Bảo Đại"

        for key in "${!leaders[@]}"; do
          TAG=$(echo "$key" | cut -d_ -f1)
          FILE=$(echo "$key" | cut -d_ -f2)
          NAME="${leaders[$key]}"

          echo "Fetching portrait for $NAME (tag: $TAG, file: $FILE.dds)"

          API_URL="https://en.wikipedia.org/w/api.php?action=query&titles=$(echo "$NAME" | sed 's/ /_/g')&prop=pageimages&format=json&pithumbsize=512"
          IMG_URL=$(curl -s "$API_URL" | grep -oP '"source":"\K[^"]+')

          if [ -n "$IMG_URL" ]; then
            mkdir -p "gfx/leaders/$TAG"
            wget -q -O "portraits/$FILE.jpg" "$IMG_URL"
            convert "portraits/$FILE.jpg" -resize 156x210\! "portraits/$FILE.bmp"
            nvcompress -bc3 "portraits/$FILE.bmp" "gfx/leaders/$TAG/$FILE.dds"
            echo "Saved to gfx/leaders/$TAG/$FILE.dds"
          else
            echo "Image not found for $NAME"
          fi
        done

    - name: Commit and Push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git pull
        git add gfx/leaders/**/*.dds
        git commit -m "Update leader portraits by country"
        git push
