name: Convert DDS to PNG and Commit

on:
  push:
    branches: [main]

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Create output directory
        run: mkdir -p convertedin

      - name: Convert .dds files to .png
        run: |
          set -e
          find . -type f -name "*.dds" | while read -r file; do
            filename=$(basename "$file" .dds)
            convert "$file" "convertedin/${filename}.png"
          done

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add convertedin/*.png
          git diff --cached --quiet || git commit -m "Auto: Update leader portraits (CHI, RAJ, VNM)"
          git push
